import React from 'react';
import {
    HomeIcon,
    ServerIcon,
    UsersIcon,
    ChipIcon,
    CubeIcon,
    CogIcon,
    DatabaseIcon,
    GlobeAltIcon,
    ClipboardListIcon,
    CodeIcon,
    ArchiveIcon,
    ChartSquareBarIcon,
    BookOpenIcon,
    SupportIcon,
    TerminalIcon,
    FolderIcon,
    ClockIcon,
    LightningBoltIcon,
    KeyIcon,
    PlayIcon,
    SwitchHorizontalIcon,
    MenuIcon,
    XIcon,
    BellIcon,
    SearchIcon,
    LogoutIcon,
    ChevronDownIcon,
    ArrowRightIcon,
} from '@heroicons/react/outline';

const icons = {
    home: HomeIcon,
    server: ServerIcon,
    users: UsersIcon,
    cpu: ChipIcon,
    cube: CubeIcon,
    settings: CogIcon,
    database: DatabaseIcon,
    globe: GlobeAltIcon,
    activity: ClipboardListIcon,
    code: CodeIcon,
    backup: ArchiveIcon,
    chart: ChartSquareBarIcon,
    book: BookOpenIcon,
    support: SupportIcon,
    console: TerminalIcon,
    files: FolderIcon,
    clock: ClockIcon,
    startup: LightningBoltIcon,
    key: KeyIcon,
    play: PlayIcon,
    network: SwitchHorizontalIcon,
    menu: MenuIcon,
    close: XIcon,
    bell: BellIcon,
    search: SearchIcon,
    logout: LogoutIcon,
    chevron: ChevronDownIcon,
    arrow: ArrowRightIcon,
};
export type IconName = keyof typeof icons;
export const serverRouteIcons: Record<string, IconName> = {
    Console: 'console',
    Files: 'files',
    Databases: 'database',
    Schedules: 'clock',
    Users: 'users',
    Backups: 'backup',
    Network: 'network',
    Startup: 'startup',
    Settings: 'settings',
    Activity: 'activity',
};
export default ({ name, className = '' }: { name: IconName; className?: string }) => {
    const Icon = icons[name];
    return <Icon className={`dc-icon ${className}`} aria-hidden={'true'} />;
};
