// Generate the shared browser tokens from the same source Tailwind consumes.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const tokens = require('../resources/diamondcrew/tokens.json');
const properties = Object.entries(tokens)
    .filter(([, value]) => typeof value === 'string')
    .map(([key, value]) => `    --dc-${key}: ${value};`);
properties.push('    --dc-gradient: linear-gradient(to right, var(--dc-primary) 0%, var(--dc-secondary) 50%, var(--dc-accent) 100%);');
fs.mkdirSync(path.join(root, 'public/branding/diamondcrew'), { recursive: true });
fs.writeFileSync(path.join(root, 'public/branding/diamondcrew/tokens.css'),
    `/* Generated by scripts/diamondcrew-theme.cjs. Edit resources/diamondcrew/tokens.json. */\n:root {\n${properties.join('\n')}\n}\n`);
